### ISSUE TITLE
Demo "Hello, World" issue

### ISSUE THREAD

**Issue by techno4u** [ramesh-366/hello-world#1]
**Compile Time error** and shows **error: expected ';' before 'return'**.

**Comment by ramesh-11** [comment]
Hello, i think that code is interesting that's why, I want to fix that code. Will you guide me related its functionality.

**Comment by techno4u** [comment]
@ramesh-11 That code is made to print "Hello, World!". But on compile time it's shows some error, that was mentioned above.

**Comment by ramesh-11** [comment]
@ramesh-366 Thanks for helping :)

**Comment by techno4u** [comment]
@ramesh-11 Welcome.
